#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# XDG
#
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS=""
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CONFIG_DIRS=""
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_RUNTIME_DIR="$TMPDIR"

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='nvim'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='neovide'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)
  $HOME/.local/bin
  $HOME/bin
  $HOME/.config/phpmon/bin
  $HOME/.config/emacs/bin
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

fpath=(
  /opt/homebrew/share/zsh/site-functions
  $fpath
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

export LESSHISTFILE="$XDG_CACHE_HOME"/less/history

#
# Ansible
#
export ANSIBLE_HOME="$XDG_DATA_HOME/ansible"

#
# MySQL
#
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history

#
# nb
#
export NB_DIR="$XDG_DATA_HOME/nb"
export NBRC_PATH="$XDG_CONFIG_HOME"/nbrc

#
# Rust
#
export CARGO_HOME="$XDG_DATA_HOME/cargo"
[[ -s "$CARGO_HOME/env" ]] && . "$CARGO_HOME/env"

#
# skim
#
export SKIM_DEFAULT_OPTIONS="--bind='ctrl-a:toggle-all'"
