#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[[ -x $HOME/.local/bin/mise ]] && eval "$($HOME/.local/bin/mise activate zsh)"

#
# Aliases
#

[[ -s "$ZDOTDIR"/.zaliases ]] && source "$ZDOTDIR"/.zaliases

#
# fuck
#

eval $(thefuck --alias)


# pnpm
export PNPM_HOME="/Users/michael/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

#
# walk
#
unalias lk
function lk {
  cd "$(walk --icons "$@")"
}

#
# tz
#
export TZ_LIST="US/Pacific;US/Central;US/Eastern;UTC;Europe/London;Europe/Istanbul"
