#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Aliases
#

[[ -s "$ZDOTDIR"/aliases.zsh ]] && source "$ZDOTDIR"/aliases.zsh

#
# asdf
#
if command -v asdf > /dev/null; then
  if [[ "$OSTYPE" == darwin* ]]; then
    source "$(brew --prefix asdf)/libexec/asdf.sh"
    fpath=(${ASDF_DIR}/completions $fpath)
  else
    source "$HOME/.asdf/asdf"
  fi
fi

#
# fuck
#
eval $(thefuck --alias)

