(("default" . ((user-emacs-directory . "~/.emacs.d")))
 ("space" . ((user-emacs-directory . "~/.spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.spacemacs.d")))))
 ("doom" . ((user-emacs-directory . "~/.doom-emacs")
            (env . (("DOOMDIR" . "~/.doom.d"))))))
